export const copy = {
  eyebrow: "operator // profile",
  statusLabel: "online",
  telemetryEyebrow: "telemetry // career peak",
  telemetryNote: "rated peaks · not live",
  basedLead: "Based in",
  basedTrail: ". Channels below are live.",
  resumeLabel: "Résumé",
  channelsEyebrow: "comms // open channel",
  channelsTitle: "Reach the operator",
  channelsHint: "tap to copy",
  emptyChannels: "Direct channels are configured via environment; use the social links below.",
  emailLabel: "Email",
  phoneLabel: "Phone",
};
