export const concurrencyModes = [
  {
    id: "race",
    name: "Race Condition",
    trigger: "Race increments",
    summary: "Four threads read the same shared value and overwrite each other, losing increments.",
    workers: 4,
    observedIncrement: 1,
    phases: ["Ready", "Read same value", "Compute +1", "Write collisions"],
    metrics: [
      { label: "Correctness", value: "Lost updates" },
      { label: "Throughput", value: "High but wrong" },
      { label: "Primitive", value: "None" },
    ],
  },
  {
    id: "mutex",
    name: "Mutex Lock",
    trigger: "Lock counter",
    summary: "Threads serialize access through a mutex so the counter is correct, but contention appears.",
    workers: 4,
    observedIncrement: 4,
    phases: ["Ready", "Acquire lock", "Increment safely", "Release lock"],
    metrics: [
      { label: "Correctness", value: "Exact" },
      { label: "Throughput", value: "Lower" },
      { label: "Primitive", value: "Mutex" },
    ],
  },
  {
    id: "atomic",
    name: "Atomic Increment",
    trigger: "Use atomic op",
    summary: "The increment becomes a single indivisible operation, preserving correctness with less lock overhead.",
    workers: 4,
    observedIncrement: 4,
    phases: ["Ready", "CPU atomic", "Cache sync", "Commit value"],
    metrics: [
      { label: "Correctness", value: "Exact" },
      { label: "Throughput", value: "High" },
      { label: "Primitive", value: "CAS/atomic" },
    ],
  },
  {
    id: "semaphore",
    name: "Semaphore",
    trigger: "Limit workers",
    summary: "A semaphore allows a bounded number of workers through the critical region at once.",
    workers: 4,
    observedIncrement: 4,
    phases: ["Ready", "Acquire permit", "Bounded work", "Return permit"],
    metrics: [
      { label: "Correctness", value: "Exact" },
      { label: "Parallelism", value: "Bounded" },
      { label: "Primitive", value: "Semaphore" },
    ],
  },
  {
    id: "queue",
    name: "Work Queue",
    trigger: "Queue tasks",
    summary: "Workers avoid shared counter races by sending increments through a queue-owned reducer.",
    workers: 4,
    observedIncrement: 4,
    phases: ["Ready", "Enqueue deltas", "Reducer drains", "Single writer"],
    metrics: [
      { label: "Correctness", value: "Exact" },
      { label: "Backpressure", value: "Visible" },
      { label: "Primitive", value: "Queue" },
    ],
  },
  {
    id: "deadlock",
    name: "Deadlock",
    trigger: "Create deadlock",
    summary: "Two threads hold different locks and wait forever for the other lock to be released.",
    workers: 2,
    observedIncrement: 0,
    phases: ["Thread A locks X", "Thread B locks Y", "A waits for Y", "B waits for X"],
    metrics: [
      { label: "Correctness", value: "No progress" },
      { label: "Throughput", value: "0" },
      { label: "Risk", value: "Circular wait" },
    ],
  },
  {
    id: "multiprocessing",
    name: "Multiprocessing",
    trigger: "Fork workers",
    summary: "Separate processes avoid the GIL for CPU-bound work, then merge results through IPC.",
    workers: 4,
    observedIncrement: 4,
    phases: ["Fork workers", "Private memory", "Parallel compute", "Merge result"],
    metrics: [
      { label: "CPU use", value: "Multi-core" },
      { label: "Memory", value: "Isolated" },
      { label: "Overhead", value: "IPC" },
    ],
  },
] as const;
