export const copy = {
  eyebrow: "cipher // decryption console",
  title: "Cipher",
  intro:
    "Decrypt the 5-letter key in six attempts. Primary = right glyph, right slot. Gold = right glyph, wrong slot.",
};

/** Answer pool — common, fair 5-letter words with a faint systems/Foundation lean. */
export const WORDS = [
  "ATOMS",
  "ORBIT",
  "RELAY",
  "NODES",
  "LOGIC",
  "CODES",
  "VAULT",
  "TRADE",
  "CYCLE",
  "DRIFT",
  "SPACE",
  "STARS",
  "PROBE",
  "CACHE",
  "QUERY",
  "ARRAY",
  "STACK",
  "QUEUE",
  "GRAPH",
  "BYTES",
  "PIXEL",
  "ROUTE",
  "LINKS",
  "TOKEN",
  "DELTA",
  "GAMMA",
  "SIGMA",
  "CHAOS",
  "MODEL",
  "PLANS",
  "FORGE",
  "SCALE",
  "EDGES",
  "FLEET",
  "COMET",
  "PULSE",
  "FIELD",
  "WAVES",
  "PHASE",
  "INDEX",
  "ATLAS",
  "REALM",
  "EPOCH",
  "ORDER",
  "TRACE",
  "NEXUS",
  "RELIC",
  "OASIS",
];

export const KEYBOARD_ROWS = ["QWERTYUIOP", "ASDFGHJKL", "ZXCVBNM"];
