import type { ProjectVisualKind } from "@/lib/resume";
import type { ProjectFlow } from "./types";

/**
 * Each project is described as a small directed flow (inputs -> processing -> output) plus an
 * ordered list of narration "steps". The scene engine plays the steps on a loop, lighting up the
 * relevant nodes and edges for each step so the viewer literally watches the problem being solved.
 */
export const projectFlows: Record<ProjectVisualKind, ProjectFlow> = {
  deployment: {
    problem: "slow environment validation",
    nodes: [
      {
        id: "a",
        label: "env a",
        detail: "secrets + config",
        point: { x: 140, y: 150 },
        role: "input",
        motif: "stack",
        width: 156,
      },
      {
        id: "b",
        label: "env b",
        detail: "secrets + config",
        point: { x: 140, y: 300 },
        role: "input",
        motif: "stack",
        width: 156,
      },
      {
        id: "diff",
        label: "diff engine",
        detail: "parallel compare",
        point: { x: 460, y: 225 },
        role: "process",
        motif: "grid",
        width: 190,
      },
      {
        id: "ok",
        label: "validated",
        detail: "release target",
        point: { x: 788, y: 225 },
        role: "output",
        motif: "check",
        width: 170,
      },
    ],
    edges: [
      ["a", "diff"],
      ["b", "diff"],
      ["diff", "ok"],
    ],
    steps: [
      { caption: "Capture env A & env B config", lit: ["a", "b"], edges: [] },
      {
        caption: "Diff secrets & config in parallel",
        lit: ["diff"],
        edges: [
          ["a", "diff"],
          ["b", "diff"],
        ],
      },
      { caption: "Surface only the real differences", lit: ["diff"], edges: [] },
      {
        caption: "Validated release, 20% less friction",
        lit: ["ok"],
        edges: [["diff", "ok"]],
        metric: "-20% friction",
      },
    ],
  },
  charging: {
    problem: "carrier-scale charging events",
    nodes: [
      {
        id: "s1",
        label: "stream 1",
        detail: "events",
        point: { x: 140, y: 130 },
        role: "input",
        motif: "events",
        width: 140,
      },
      {
        id: "s2",
        label: "stream 2",
        detail: "events",
        point: { x: 140, y: 220 },
        role: "input",
        motif: "events",
        width: 140,
      },
      {
        id: "s3",
        label: "stream 3",
        detail: "events",
        point: { x: 140, y: 310 },
        role: "input",
        motif: "events",
        width: 140,
      },
      {
        id: "rate",
        label: "rating core",
        detail: "rate + order",
        point: { x: 455, y: 220 },
        role: "process",
        motif: "ring",
        width: 196,
      },
      {
        id: "led",
        label: "ledger",
        detail: "subscriber ledger",
        point: { x: 790, y: 220 },
        role: "output",
        motif: "rows",
        width: 188,
      },
    ],
    edges: [
      ["s1", "rate"],
      ["s2", "rate"],
      ["s3", "rate"],
      ["rate", "led"],
    ],
    steps: [
      { caption: "Ingest the carrier event firehose", lit: ["s1", "s2", "s3"], edges: [] },
      {
        caption: "Rate & charge 600K+ records/sec",
        lit: ["rate"],
        edges: [
          ["s1", "rate"],
          ["s2", "rate"],
          ["s3", "rate"],
        ],
      },
      { caption: "Commit to the subscriber ledger", lit: ["led"], edges: [["rate", "led"]] },
      { caption: "600K+ records/sec, 100M+ subscribers", lit: ["led"], edges: [], metric: "600K/s" },
    ],
  },
  telecom: {
    problem: "post-acquisition platform migration",
    nodes: [
      {
        id: "ue",
        label: "subscriber",
        detail: "customer action",
        point: { x: 120, y: 235 },
        role: "input",
        motif: "stack",
        width: 150,
      },
      {
        id: "bss",
        label: "BSS · care",
        detail: "care layer",
        point: { x: 350, y: 150 },
        role: "process",
        motif: "grid",
        width: 166,
      },
      {
        id: "oss",
        label: "OSS · network",
        detail: "network layer",
        point: { x: 580, y: 270 },
        role: "process",
        motif: "grid",
        width: 172,
      },
      {
        id: "bill",
        label: "billing",
        detail: "provisioned",
        point: { x: 800, y: 150 },
        role: "output",
        motif: "check",
        width: 150,
      },
    ],
    edges: [
      ["ue", "bss"],
      ["bss", "oss"],
      ["oss", "bill"],
    ],
    steps: [
      { caption: "Subscriber action is captured", lit: ["ue"], edges: [] },
      { caption: "Bridge into the BSS care layer", lit: ["bss"], edges: [["ue", "bss"]] },
      { caption: "Hand off to the OSS network", lit: ["oss"], edges: [["bss", "oss"]] },
      {
        caption: "Service provisioned & billed",
        lit: ["bill"],
        edges: [["oss", "bill"]],
        metric: "migrated",
      },
    ],
  },
  billing: {
    problem: "daily billing aggregation",
    nodes: [
      {
        id: "r1",
        label: "records a",
        detail: "billing records",
        point: { x: 140, y: 155 },
        role: "input",
        motif: "stack",
        width: 162,
      },
      {
        id: "r2",
        label: "records b",
        detail: "billing records",
        point: { x: 140, y: 300 },
        role: "input",
        motif: "stack",
        width: 162,
      },
      {
        id: "agg",
        label: "aggregate",
        detail: "sync boundary",
        point: { x: 460, y: 228 },
        role: "process",
        motif: "bars",
        width: 188,
      },
      {
        id: "view",
        label: "subscriber view",
        detail: "unified view",
        point: { x: 790, y: 228 },
        role: "output",
        motif: "rows",
        width: 188,
      },
    ],
    edges: [
      ["r1", "agg"],
      ["r2", "agg"],
      ["agg", "view"],
    ],
    steps: [
      { caption: "Pull 5M+ daily billing records", lit: ["r1", "r2"], edges: [] },
      {
        caption: "Aggregate at the sync boundary",
        lit: ["agg"],
        edges: [
          ["r1", "agg"],
          ["r2", "agg"],
        ],
      },
      { caption: "Reconcile into one record", lit: ["agg"], edges: [] },
      {
        caption: "Unified view, 50% faster sync",
        lit: ["view"],
        edges: [["agg", "view"]],
        metric: "+50% sync",
      },
    ],
  },
  ordering: {
    problem: "enterprise order throughput",
    nodes: [
      {
        id: "q",
        label: "order queue",
        detail: "work queue",
        point: { x: 135, y: 220 },
        role: "input",
        motif: "stack",
        width: 160,
      },
      {
        id: "orch",
        label: "orchestrator",
        detail: "split work",
        point: { x: 375, y: 220 },
        role: "process",
        motif: "grid",
        width: 176,
      },
      {
        id: "w1",
        label: "worker 1",
        detail: "bounded work",
        point: { x: 600, y: 135 },
        role: "process",
        motif: "ring",
        width: 150,
      },
      {
        id: "w2",
        label: "worker 2",
        detail: "bounded work",
        point: { x: 600, y: 300 },
        role: "process",
        motif: "ring",
        width: 150,
      },
      {
        id: "done",
        label: "fulfilled",
        detail: "orders done",
        point: { x: 805, y: 220 },
        role: "output",
        motif: "check",
        width: 150,
      },
    ],
    edges: [
      ["q", "orch"],
      ["orch", "w1"],
      ["orch", "w2"],
      ["w1", "done"],
      ["w2", "done"],
    ],
    steps: [
      { caption: "Buffer enterprise orders", lit: ["q"], edges: [] },
      { caption: "Orchestrate & split the work", lit: ["orch"], edges: [["q", "orch"]] },
      {
        caption: "Run workers in parallel",
        lit: ["w1", "w2"],
        edges: [
          ["orch", "w1"],
          ["orch", "w2"],
        ],
      },
      {
        caption: "4x throughput, 99.999% uptime",
        lit: ["done"],
        edges: [
          ["w1", "done"],
          ["w2", "done"],
        ],
        metric: "4x",
      },
    ],
  },
  media: {
    problem: "serial media processing",
    nodes: [
      {
        id: "m",
        label: "media batch",
        detail: "raw media",
        point: { x: 130, y: 220 },
        role: "input",
        motif: "stack",
        width: 156,
      },
      {
        id: "p1",
        label: "ffmpeg 1",
        detail: "encode",
        point: { x: 415, y: 130 },
        role: "process",
        motif: "grid",
        width: 130,
      },
      {
        id: "p2",
        label: "ffmpeg 2",
        detail: "encode",
        point: { x: 415, y: 300 },
        role: "process",
        motif: "grid",
        width: 130,
      },
      {
        id: "p3",
        label: "ffmpeg 3",
        detail: "encode",
        point: { x: 600, y: 130 },
        role: "process",
        motif: "grid",
        width: 130,
      },
      {
        id: "p4",
        label: "ffmpeg 4",
        detail: "encode",
        point: { x: 600, y: 300 },
        role: "process",
        motif: "grid",
        width: 130,
      },
      {
        id: "out",
        label: "assets",
        detail: "processed",
        point: { x: 800, y: 220 },
        role: "output",
        motif: "bars",
        width: 150,
      },
    ],
    edges: [
      ["m", "p1"],
      ["m", "p2"],
      ["m", "p3"],
      ["m", "p4"],
      ["p1", "out"],
      ["p2", "out"],
      ["p3", "out"],
      ["p4", "out"],
    ],
    steps: [
      { caption: "Queue a high-volume media batch", lit: ["m"], edges: [] },
      {
        caption: "Fan out across the worker pool",
        lit: ["p1", "p2", "p3", "p4"],
        edges: [
          ["m", "p1"],
          ["m", "p2"],
          ["m", "p3"],
          ["m", "p4"],
        ],
      },
      { caption: "Encode frames concurrently", lit: ["p1", "p2", "p3", "p4"], edges: [] },
      {
        caption: "~300% throughput vs serial",
        lit: ["out"],
        edges: [
          ["p1", "out"],
          ["p2", "out"],
          ["p3", "out"],
          ["p4", "out"],
        ],
        metric: "+300%",
      },
    ],
  },
  pipeline: {
    problem: "manual training-data prep",
    nodes: [
      {
        id: "ing",
        label: "ingest",
        detail: "daily records",
        point: { x: 135, y: 220 },
        role: "input",
        motif: "stack",
        width: 156,
      },
      {
        id: "clean",
        label: "clean",
        detail: "normalize",
        point: { x: 355, y: 220 },
        role: "process",
        motif: "rows",
        width: 156,
      },
      {
        id: "store",
        label: "store",
        detail: "curated set",
        point: { x: 570, y: 220 },
        role: "process",
        motif: "stack",
        width: 156,
      },
      {
        id: "train",
        label: "train set",
        detail: "model ready",
        point: { x: 790, y: 220 },
        role: "output",
        motif: "bars",
        width: 162,
      },
    ],
    edges: [
      ["ing", "clean"],
      ["clean", "store"],
      ["store", "train"],
    ],
    steps: [
      { caption: "Ingest 1000+ daily records", lit: ["ing"], edges: [] },
      { caption: "Normalize & validate", lit: ["clean"], edges: [["ing", "clean"]] },
      { caption: "Store the curated dataset", lit: ["store"], edges: [["clean", "store"]] },
      {
        caption: "Training set, 70% less prep",
        lit: ["train"],
        edges: [["store", "train"]],
        metric: "-70% prep",
      },
    ],
  },
  monetization: {
    problem: "usage-to-revenue path",
    nodes: [
      {
        id: "use",
        label: "usage",
        detail: "usage records",
        point: { x: 140, y: 155 },
        role: "input",
        motif: "events",
        width: 160,
      },
      {
        id: "rules",
        label: "plan rules",
        detail: "pricing plans",
        point: { x: 140, y: 300 },
        role: "input",
        motif: "rows",
        width: 160,
      },
      {
        id: "meter",
        label: "metering",
        detail: "rate usage",
        point: { x: 460, y: 228 },
        role: "process",
        motif: "gauge",
        width: 182,
      },
      {
        id: "inv",
        label: "invoice",
        detail: "+ revenue",
        point: { x: 790, y: 228 },
        role: "output",
        motif: "rows",
        width: 186,
      },
    ],
    edges: [
      ["use", "meter"],
      ["rules", "meter"],
      ["meter", "inv"],
    ],
    steps: [
      { caption: "Collect usage + plan rules", lit: ["use", "rules"], edges: [] },
      {
        caption: "Meter usage against plans",
        lit: ["meter"],
        edges: [
          ["use", "meter"],
          ["rules", "meter"],
        ],
      },
      { caption: "Compute the billable amount", lit: ["meter"], edges: [] },
      { caption: "$200K early revenue", lit: ["inv"], edges: [["meter", "inv"]], metric: "$200K" },
    ],
  },
  system: {
    problem: "system trade-off",
    nodes: [
      {
        id: "in",
        label: "inputs",
        detail: "signals",
        point: { x: 160, y: 225 },
        role: "input",
        motif: "stack",
        width: 160,
      },
      {
        id: "mod",
        label: "model",
        detail: "trade-off",
        point: { x: 460, y: 215 },
        role: "process",
        motif: "ring",
        width: 176,
      },
      {
        id: "out",
        label: "lab view",
        detail: "result",
        point: { x: 780, y: 225 },
        role: "output",
        motif: "rows",
        width: 166,
      },
    ],
    edges: [
      ["in", "mod"],
      ["mod", "out"],
    ],
    steps: [
      { caption: "Feed the system inputs", lit: ["in"], edges: [] },
      { caption: "Model the trade-off", lit: ["mod"], edges: [["in", "mod"]] },
      { caption: "Read out the result", lit: ["out"], edges: [["mod", "out"]], metric: "trace" },
    ],
  },
  reporting: {
    problem: "write-optimized store, read-hostile",
    nodes: [
      {
        id: "cron",
        label: "k8s cron",
        detail: "daily + weekly",
        point: { x: 135, y: 150 },
        role: "input",
        motif: "events",
        width: 150,
      },
      {
        id: "cass",
        label: "Cassandra · DSE",
        detail: "~5TB/day",
        point: { x: 135, y: 300 },
        role: "input",
        motif: "rows",
        width: 176,
      },
      {
        id: "spark",
        label: "Spark + YAML",
        detail: "aggregate",
        point: { x: 430, y: 225 },
        role: "process",
        motif: "grid",
        width: 190,
      },
      {
        id: "tbl",
        label: "report tables",
        detail: "read-optimized",
        point: { x: 645, y: 225 },
        role: "process",
        motif: "stack",
        width: 150,
      },
      {
        id: "graf",
        label: "Grafana",
        detail: "dashboards",
        point: { x: 805, y: 225 },
        role: "output",
        motif: "bars",
        width: 150,
      },
    ],
    edges: [
      ["cron", "spark"],
      ["cass", "spark"],
      ["spark", "tbl"],
      ["tbl", "graf"],
    ],
    steps: [
      { caption: "Cron fires the daily & weekly jobs", lit: ["cron", "cass"], edges: [] },
      {
        caption: "Spark aggregates via YAML-defined SQL",
        lit: ["spark"],
        edges: [
          ["cron", "spark"],
          ["cass", "spark"],
        ],
      },
      { caption: "Rank & roll up: COUNT, max_by, rank", lit: ["spark"], edges: [] },
      { caption: "Write read-optimized report tables", lit: ["tbl"], edges: [["spark", "tbl"]] },
      {
        caption: "Grafana serves the dashboards",
        lit: ["graf"],
        edges: [["tbl", "graf"]],
        metric: "5TB/day",
      },
    ],
  },
};
